# Generated by Django 4.2.25 on 2025-11-06 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_rename_capacity_event_capacity_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_events_as_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
