"""
Django settings for knowa_server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import configparser
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

config = configparser.ConfigParser()
config.read(os.path.join(BASE_DIR, 'my.cnf'))

EMAIL_HOST_USER = config.get('email', 'EMAIL_USER', fallback=None)
EMAIL_HOST_PASSWORD = config.get('email', 'EMAIL_PASS', fallback=None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k7x))07ic+i^fov)pa4y-7&lfh(8z_v_scm%1)+gs9^7d!wy4k'

# SECURITY WARNING: don't run with debug turned on in production!
# IMPORTANT: In a real production app, set this to False via environment variable
DEBUG = True

# --- UPDATED: Allow all hosts so Railway URL works ---
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 3rd Party Apps
    'rest_framework',
    'rest_framework_simplejwt', # For token login
    'corsheaders',

    # My Apps
    'users.apps.UsersConfig',
    'events',
    'chat.apps.ChatConfig',
    'donations',
    'chatbot',

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- ADDED: For static files on Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'knowa_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'knowa_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- UPDATED: Smart Database Switch ---
# If running on Railway, use their Database. If Local, use yours.
if 'RAILWAY_ENVIRONMENT' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQLDATABASE'),
            'USER': os.environ.get('MYSQLUSER'),
            'PASSWORD': os.environ.get('MYSQLPASSWORD'),
            'HOST': os.environ.get('MYSQLHOST'),
            'PORT': os.environ.get('MYSQLPORT'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    # Running Locally (Your Laptop)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'knowa_db',                 # The database name you created
            'USER': 'root',                    # Your phpMyAdmin username
            'PASSWORD': '',                    # Your phpMyAdmin password
            'HOST': '127.0.0.1',               # Localhost
            'PORT': '3306',                    # Default MySQL port
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- UPDATED: Static Files Configuration for Production ---
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Configure Django REST Framework to use JWTs for authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ]
}

SIMPLE_JWT = {
    # This makes the user stay logged in for 30 days
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    
    # The refresh token lasts 60 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    
    # Security settings
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Settings for user-uploaded files (like profile pics or event photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# knowa_server/settings.py

# --- EMAIL CONFIGURATION (SSL VERSION) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465  # <--- CHANGED TO 465
EMAIL_USE_TLS = False  # <--- TURN OFF TLS
EMAIL_USE_SSL = True   # <--- TURN ON SSL (More reliable)

# Get secrets from Railway Variables
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')

# Fallback for Local Development
if not EMAIL_HOST_USER:
    try:
        config = configparser.ConfigParser()
        config.read(os.path.join(BASE_DIR, 'my.cnf'))
        EMAIL_HOST_USER = config.get('email', 'EMAIL_USER', fallback=None)
        EMAIL_HOST_PASSWORD = config.get('email', 'EMAIL_PASS', fallback=None)
    except:
        pass

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# --- UPDATED: Trust Railway Domain ---
# This prevents "Forbidden (403)" errors on the Admin Login page in production
CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']