# Generated by Django 4.2.25 on 2026-01-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_meeting'),
        ('users', '0014_notification'),
        ('chat', '0003_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='description',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='users.interview'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('EVENT', 'Event Group'), ('INTERVIEW', 'Interview Room'), ('DIRECT', 'Direct Message')], default='EVENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='events.event'),
        ),
    ]
