# Generated by Django 4.2.25 on 2025-11-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_status',
            field=models.CharField(choices=[('PUBLIC', 'Public User'), ('PENDING', 'Pending Member'), ('INTERVIEW', 'Interview'), ('MEMBER', 'NGO Member'), ('REJECTED', 'Rejected')], default='PUBLIC', max_length=10),
        ),
    ]
