# Generated by Django 4.2.25 on 2025-11-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_interests_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tac_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tac_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
