# Generated by Django 4.2.25 on 2025-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_status',
            field=models.CharField(choices=[('PUBLIC', 'Public User'), ('PENDING', 'Pending Member'), ('INTERVIEW', 'Interview'), ('APPROVED_UNPAID', 'Approved (Unpaid)'), ('MEMBER', 'NGO Member'), ('REJECTED', 'Rejected')], default='PUBLIC', max_length=20),
        ),
    ]
