# Generated by Django 4.2.25 on 2025-11-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_payment_receipt_alter_user_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_status',
            field=models.CharField(choices=[('PUBLIC', 'Public User'), ('PENDING', 'Pending Member'), ('INTERVIEW', 'Interview'), ('APPROVED_UNPAID', 'Approved (Unpaid)'), ('VOLUNTEER', 'Volunteer'), ('MEMBER', 'NGO Member'), ('REJECTED', 'Rejected')], default='PUBLIC', max_length=20),
        ),
    ]
