# Generated by Django 4.2.25 on 2025-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='application_type',
            field=models.CharField(blank=True, choices=[('VOLUNTEER', 'Project-Based Volunteer'), ('MEMBERSHIP', 'Full Membership')], max_length=20, null=True),
        ),
    ]
