# Generated by Django 4.2.25 on 2025-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
