# Generated by Django 4.2.25 on 2025-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_interview_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
