# Generated by Django 4.2.25 on 2026-01-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='report',
            field=models.TextField(blank=True, help_text="Interviewer's notes/report", null=True),
        ),
    ]
