# Generated by Django 4.2.25 on 2026-01-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_interview_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('criteria_type', models.CharField(choices=[('EVENT', 'Event Joined'), ('DONATION', 'Donation Made')], max_length=20)),
                ('threshold', models.IntegerField(help_text='Count needed to earn this badge')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_donations_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_events_joined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earned_badges',
            field=models.ManyToManyField(blank=True, related_name='holders', to='users.badge'),
        ),
    ]
