# Generated by Django 4.2.25 on 2025-12-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
